export const enum BiddingType {
  PO_ORDER_BIDDING = 'PO_ORDER_BIDDING',

  NON_MATERIAL_BIDDING = 'NON_MATERIAL_BIDDING',

  MATERIAL_BIDDING = 'MATERIAL_BIDDING',

  SPECIAL_PROJECT_BIDDING = 'SPECIAL_PROJECT_BIDDING',
}
